### PR TITLE
Adds new github actions workflows and hawkscan configuration file for guidetorial

### PR DESCRIPTION
**Pull request by HCloward**
Aaron and I are working on an end-to-end demo of StackHawk that does not require downloading anything or altering your local environment. We want to use the Javaspringvulny app as part of this guidetorial, but it will need some new github actions workflows and a new stackhawk configuration file.

### CODE REVIEW

**Review by kcberg — APPROVED** [review]
👍

**Comment by sgerlach** [comment]
Curious if we should make this .github file something else, like .github-example so it's not triggering that actual workflow in this project....

Then the instructions could be rename the .github-example directory to .github and you'll enable github actions.... blah

**Comment by HCloward** [comment]
> Curious if we should make this .github file something else, like .github-example so it's not triggering that actual workflow in this project....
> 
> Then the instructions could be rename the .github-example directory to .github and you'll enable github actions.... blah

@sgerlach I believe engineering uses the .github folder for testing purposes for the project itself. Also, when I created a fork of the repo, the GitHub Actions workflows did not automatically start being applied - I had to acknowledge them and click a button saying I was ok with them running. 

image

**Comment by HCloward** [comment]
ugh, I accidentally closed this by deleting the original fork in my profile. I opened a new one - #36

**Pull request closed without merging**
